version: '3.5'
services:
 web_dev:
  build: .
  ports:
   - "4000:4000"
  volumes:
   - .:/app
  environment:
   - ENV=development
   - PORT=4000
   - DB=mongodb://<to-change>@ds044979.mlab.com:44979/dev_logiciel_final?retryWrites=false
 
